config = {
    "sample_rate": 44100,
    "duration": 10.0,
    "oscillators": [
        {
            "index": 0,
            "wave_type": "sine",
            "amp": 0.5,
            "freq": 50.0,
            "phase": 0.0,
            "pm_depth": 1.0,
            "additive_harmonics": 1,
            "enable": True,
            "output_to_master": True,
        },
        {
            "index": 1,
            "wave_type": "sine",
            "amp": 0.2,
            "freq": 1100.0,
            "phase": 0.0,
            "pm_depth": 1.0,
            "additive_harmonics": 32,
            "enable": True,
            "output_to_master": False,
        },
        {
            "index": 2,
            "wave_type": "sine",
            "amp": 0.2,
            "freq": 2.0,
            "phase": 0.0,
            "pm_depth": 1.0,
            "additive_harmonics": 1,
            "enable": True,
            "output_to_master": False,
        },
        {
            "index": 3,
            "wave_type": "sine",
            "amp": 0.2,
            "freq": 440.0,
            "phase": 0.0,
            "pm_depth": 1.0,
            "additive_harmonics": 1,
            "enable": False,
            "output_to_master": False,
        },
        {
            "index": 4,
            "wave_type": "sine",
            "amp": 0.2,
            "freq": 440.0,
            "phase": 0.0,
            "pm_depth": 1.0,
            "additive_harmonics": 1,
            "enable": False,
            "output_to_master": False,
        },
        {
            "index": 5,
            "wave_type": "sine",
            "amp": 0.2,
            "freq": 440.0,
            "phase": 0.0,
            "pm_depth": 1.0,
            "additive_harmonics": 1,
            "enable": False,
            "output_to_master": False,
        },
    ],
    "pm_matrix": [
        [0, 2, 6, 0, 0, 2],
        [3, 0, 0, 0, 0, 0],
        [2, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
    ],
    "Volume_Envs": [
        [0.4, 3.8, 0.1, 0.5],
        [0.4, 0.6, 0.2, 0.5],
        [0.4, 0.8, 0.7, 0.5],
        [0.4, 0.8, 0.7, 0.5],
        [0.4, 0.8, 0.7, 0.5],
        [0.4, 0.8, 0.7, 0.5],
    ],
    "pm_Envs": [
        [0.6, 0.8, 0.7, 0.5],
        [0.2, 0.8, 0.7, 0.5],
        [0.2, 0.8, 0.7, 0.5],
        [0.2, 0.8, 0.7, 0.5],
        [0.2, 0.8, 0.7, 0.5],
        [0.2, 0.8, 0.7, 0.5],
    ],
}
